version: '3.8'

services:
  backend:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
      - ./logs:/app/logs
    environment:
      - DB_URL=${DB_URL}
      - SECRET_KEY=${SECRET_KEY}
      - STRIPE_SECRET=${STRIPE_SECRET}
      - PAYPAL_WEBHOOK_ID=${PAYPAL_WEBHOOK_ID}
      - PAYPAL_CLIENT_ID=${PAYPAL_CLIENT_ID}
      - PAYPAL_CLIENT_SECRET=${PAYPAL_CLIENT_SECRET}
    depends_on:
      - db
  frontend:
     build:
      context: .
      dockerfile: 
        Dockerfile.frontend
     container_name: 
       shaiya-frontend
     depends_on: 
       backend        # <-- usa il nome del tuo servizio FastAPI
     ports: 
       "8080:8080"    # Frontend raggiungibile su http://localhost:8080/
     networks: 
       shaiya         # <-- usa la rete già definita nel tuo compose, oppure shaiya:{}
# Per sviluppo live senza rebuild, puoi scommentare:# volumes:#   - ./Frontend:/usr/share/nginx/html:ro#   - ./nginx.conf:/etc/nginx/nginx.conf:ro
    
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
